# [Mebel]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [Mebel]    Script Date: 18.06.2025 3:37:42 ******/
CREATE DATABASE [Mebel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mebel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Mebel.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Mebel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Mebel_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Mebel] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mebel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Mebel] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Mebel] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Mebel] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Mebel] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Mebel] SET ARITHABORT OFF 
GO
ALTER DATABASE [Mebel] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Mebel] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Mebel] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Mebel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Mebel] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Mebel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Mebel] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Mebel] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Mebel] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Mebel] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Mebel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Mebel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Mebel] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Mebel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Mebel] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Mebel] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Mebel] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Mebel] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Mebel] SET  MULTI_USER 
GO
ALTER DATABASE [Mebel] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Mebel] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Mebel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Mebel] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Mebel] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Mebel] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Mebel] SET QUERY_STORE = ON
GO
ALTER DATABASE [Mebel] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Material_type$]

In [0]:
USE [Mebel]
GO

In [0]:
/****** Object:  Table [dbo].[Material_type$]    Script Date: 18.06.2025 3:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Material_type$](
	[Type_material] [nvarchar](255) NOT NULL,
	[Brak ] [float] NULL,
 CONSTRAINT [PK_Material_type$] PRIMARY KEY CLUSTERED 
(
	[Type_material] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Partner_products$]

In [0]:
/****** Object:  Table [dbo].[Partner_products$]    Script Date: 18.06.2025 3:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Partner_products$](
	[Production] [nvarchar](255) NULL,
	[Articul] [int] NOT NULL,
	[Name_part] [nvarchar](255) NULL,
	[kolvo] [float] NULL,
	[date] [datetime] NULL
) ON [PRIMARY]
GO

# [dbo].[Partners$]

In [0]:
/****** Object:  Table [dbo].[Partners$]    Script Date: 18.06.2025 3:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Partners$](
	[INN] [float] NULL,
	[Type_part] [nvarchar](255) NULL,
	[Name_part] [nvarchar](255) NOT NULL,
	[Director] [nvarchar](255) NULL,
	[email] [nvarchar](255) NULL,
	[telephone] [nvarchar](255) NULL,
	[adress] [nvarchar](255) NULL,
	[Raiting] [float] NULL,
 CONSTRAINT [PK_Partners$] PRIMARY KEY CLUSTERED 
(
	[Name_part] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[PartnerTypes$]

In [0]:
/****** Object:  Table [dbo].[PartnerTypes$]    Script Date: 18.06.2025 3:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PartnerTypes$](
	[Type_part] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_PartnerTypes$] PRIMARY KEY CLUSTERED 
(
	[Type_part] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Product_type$]

In [0]:
/****** Object:  Table [dbo].[Product_type$]    Script Date: 18.06.2025 3:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product_type$](
	[Type_product] [nvarchar](255) NOT NULL,
	[koef] [float] NULL,
 CONSTRAINT [PK_Product_type$] PRIMARY KEY CLUSTERED 
(
	[Type_product] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Products$]

In [0]:
/****** Object:  Table [dbo].[Products$]    Script Date: 18.06.2025 3:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products$](
	[Articul] [int] NOT NULL,
	[Type_product] [nvarchar](255) NOT NULL,
	[name_product] [nvarchar](255) NULL,
	[min_ex] [float] NULL,
 CONSTRAINT [PK_Products$] PRIMARY KEY CLUSTERED 
(
	[Articul] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Material_type$]

In [0]:
INSERT [dbo].[Material_type$] ([Type_material], [Brak ]) VALUES (N'bvf', 1)
INSERT [dbo].[Material_type$] ([Type_material], [Brak ]) VALUES (N'Тип материала 1', 0.001)
INSERT [dbo].[Material_type$] ([Type_material], [Brak ]) VALUES (N'Тип материала 2', 0.0095)
INSERT [dbo].[Material_type$] ([Type_material], [Brak ]) VALUES (N'Тип материала 3', 0.0028)
INSERT [dbo].[Material_type$] ([Type_material], [Brak ]) VALUES (N'Тип материала 4', 0.0055)
GO

# [dbo].[Partner_products$]

In [0]:
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Паркетная доска Ясень темный однополосная 14 мм', 8758385, N'База Строитель', 15500, CAST(N'2023-03-23T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Ламинат Дуб дымчато-белый 33 класс 12 мм', 7750282, N'База Строитель', 12350, CAST(N'2023-12-18T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Ламинат Дуб серый 32 класс 8 мм с фаской', 7028748, N'База Строитель', 37400, CAST(N'2024-06-07T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Инженерная доска Дуб Французская елка однополосная 12 мм', 8858958, N'Паркет 29', 35000, CAST(N'2022-12-02T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Пробковое напольное клеевое покрытие 32 класс 4 мм', 5012543, N'Паркет 29', 1250, CAST(N'2023-05-17T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Ламинат Дуб дымчато-белый 33 класс 12 мм', 7750282, N'Паркет 29', 1000, CAST(N'2024-06-07T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Паркетная доска Ясень темный однополосная 14 мм', 8758385, N'Паркет 29', 7550, CAST(N'2024-07-01T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Паркетная доска Ясень темный однополосная 14 мм', 8758385, N'Стройсервис', 7250, CAST(N'2023-01-22T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Инженерная доска Дуб Французская елка однополосная 12 мм', 8858958, N'Стройсервис', 2500, CAST(N'2024-07-05T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Ламинат Дуб серый 32 класс 8 мм с фаской', 7028748, N'Ремонт и отделка', 59050, CAST(N'2023-03-20T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Ламинат Дуб дымчато-белый 33 класс 12 мм', 7750282, N'Ремонт и отделка', 37200, CAST(N'2024-03-12T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Пробковое напольное клеевое покрытие 32 класс 4 мм', 5012543, N'Ремонт и отделка', 4500, CAST(N'2024-05-14T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Ламинат Дуб дымчато-белый 33 класс 12 мм', 7750282, N'МонтажПро', 50000, CAST(N'2023-09-19T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Ламинат Дуб серый 32 класс 8 мм с фаской', 7028748, N'МонтажПро', 670000, CAST(N'2023-11-10T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Паркетная доска Ясень темный однополосная 14 мм', 8758385, N'МонтажПро', 35000, CAST(N'2024-04-15T00:00:00.000' AS DateTime))
INSERT [dbo].[Partner_products$] ([Production], [Articul], [Name_part], [kolvo], [date]) VALUES (N'Инженерная доска Дуб Французская елка однополосная 12 мм', 8858958, N'МонтажПро', 25000, CAST(N'2024-06-12T00:00:00.000' AS DateTime))
GO

# [dbo].[Partners$]

In [0]:
INSERT [dbo].[Partners$] ([INN], [Type_part], [Name_part], [Director], [email], [telephone], [adress], [Raiting]) VALUES (2222455179, N'ЗАО', N'База Строитель', N'Иванова Александра Ивановна', N'aleksandraivanova@ml.ru', N'493 123 45 67', N'652050, Кемеровская область, город Юрга, ул. Лесная, 15', 7)
INSERT [dbo].[Partners$] ([INN], [Type_part], [Name_part], [Director], [email], [telephone], [adress], [Raiting]) VALUES (123, N'йцу', N'йуц', N'йуц', N'ууууу', N'33333', N'йцу', 1)
INSERT [dbo].[Partners$] ([INN], [Type_part], [Name_part], [Director], [email], [telephone], [adress], [Raiting]) VALUES (123, N'Данёк', N'йцу', N'йцу', N'йцу', N'123', N'123', 2)
INSERT [dbo].[Partners$] ([INN], [Type_part], [Name_part], [Director], [email], [telephone], [adress], [Raiting]) VALUES (5552431140, N'ЗАО', N'МонтажПро', N'Степанов Степан Сергеевич', N'stepanov@stepan.ru', N'912 888 33 33', N'309500, Белгородская область, город Старый Оскол, ул. Рабочая, 122', 10)
INSERT [dbo].[Partners$] ([INN], [Type_part], [Name_part], [Director], [email], [telephone], [adress], [Raiting]) VALUES (3333888520, N'ООО', N'Паркет 29', N'Петров Василий Петрович', N'vppetrov@vl.ru', N'987 123 56 78', N'164500, Архангельская область, город Северодвинск, ул. Строителей, 18', 7)
INSERT [dbo].[Partners$] ([INN], [Type_part], [Name_part], [Director], [email], [telephone], [adress], [Raiting]) VALUES (1111520857, N'ОАО', N'Ремонт и отделка', N'Воробьева Екатерина Валерьевна', N'ekaterina.vorobeva@ml.ru', N'444 222 33 11', N'143960, Московская область, город Реутов, ул. Свободы, 51', 5)
INSERT [dbo].[Partners$] ([INN], [Type_part], [Name_part], [Director], [email], [telephone], [adress], [Raiting]) VALUES (4440391035, N'ПАО', N'Стройсервис', N'Соловьев Андрей Николаевич', N'ansolovev@st.ru', N'812 223 32 00', N'188910, Ленинградская область, город Приморск, ул. Парковая, 21', 7)
GO

# [dbo].[PartnerTypes$]

In [0]:
INSERT [dbo].[PartnerTypes$] ([Type_part]) VALUES (N'ЗАО')
INSERT [dbo].[PartnerTypes$] ([Type_part]) VALUES (N'ОАО')
INSERT [dbo].[PartnerTypes$] ([Type_part]) VALUES (N'ООО')
INSERT [dbo].[PartnerTypes$] ([Type_part]) VALUES (N'ПАО')
GO

# [dbo].[Product_type$]

In [0]:
INSERT [dbo].[Product_type$] ([Type_product], [koef]) VALUES (N'Ламинат', 2.35)
INSERT [dbo].[Product_type$] ([Type_product], [koef]) VALUES (N'Массивная доска', 5.15)
INSERT [dbo].[Product_type$] ([Type_product], [koef]) VALUES (N'Паркетная доска', 4.34)
INSERT [dbo].[Product_type$] ([Type_product], [koef]) VALUES (N'Пробковое покрытие', 1.5)
GO

# [dbo].[Products$]

In [0]:
INSERT [dbo].[Products$] ([Articul], [Type_product], [name_product], [min_ex]) VALUES (5012543, N'Пробковое покрытие', N'Пробковое напольное клеевое покрытие 32 класс 4 мм', 5450.59)
INSERT [dbo].[Products$] ([Articul], [Type_product], [name_product], [min_ex]) VALUES (7028748, N'Ламинат', N'Ламинат Дуб серый 32 класс 8 мм с фаской', 3890.41)
INSERT [dbo].[Products$] ([Articul], [Type_product], [name_product], [min_ex]) VALUES (7750282, N'Ламинат', N'Ламинат Дуб дымчато-белый 33 класс 12 мм', 1799.33)
INSERT [dbo].[Products$] ([Articul], [Type_product], [name_product], [min_ex]) VALUES (8758385, N'Паркетная доска', N'Паркетная доска Ясень темный однополосная 14 мм', 4456.9)
INSERT [dbo].[Products$] ([Articul], [Type_product], [name_product], [min_ex]) VALUES (8858958, N'Паркетная доска', N'Инженерная доска Дуб Французская елка однополосная 12 мм', 7330.99)
GO

# [FK_Partner_products$_Partners$]

In [0]:
ALTER TABLE [dbo].[Partner_products$]  WITH CHECK ADD  CONSTRAINT [FK_Partner_products$_Partners$] FOREIGN KEY([Name_part])
REFERENCES [dbo].[Partners$] ([Name_part])
GO
ALTER TABLE [dbo].[Partner_products$] CHECK CONSTRAINT [FK_Partner_products$_Partners$]
GO

# [FK_Partner_products$_Products$]

In [0]:
ALTER TABLE [dbo].[Partner_products$]  WITH CHECK ADD  CONSTRAINT [FK_Partner_products$_Products$] FOREIGN KEY([Articul])
REFERENCES [dbo].[Products$] ([Articul])
GO
ALTER TABLE [dbo].[Partner_products$] CHECK CONSTRAINT [FK_Partner_products$_Products$]
GO

# [FK_Products$_Product_type$]

In [0]:
ALTER TABLE [dbo].[Products$]  WITH CHECK ADD  CONSTRAINT [FK_Products$_Product_type$] FOREIGN KEY([Type_product])
REFERENCES [dbo].[Product_type$] ([Type_product])
GO
ALTER TABLE [dbo].[Products$] CHECK CONSTRAINT [FK_Products$_Product_type$]
GO

# [Mebel]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [Mebel] SET  READ_WRITE 
GO